### PR TITLE
Fix #4656: Improve diagnostics for invalid proto files

### LINKED ISSUE #4656: Improve diagnostics for invalid proto files
When the proto file is invalid, the `grpc` command crashes. It would be better if we can have proper error messages for the failures. 

For example, in my case, the issue was I hadn't defined a type that I had used in another type:
```proto3
message PaginatedUser {
    int64 count = 1;
    repeated User list = 2;
    Pagination pagination = 3;
}
```
The `User` wasn't defined in the file. The output from the `grpc` command was as follows:
```
bal grpc --input resources/user_service.proto
Downloading the protoc executor file - protoc-3.21.7-osx-x86_64.exe
Download successfully completed. Executor file path - /var/folders/_w/76qx789d5hj633snw3c8fswr0000gp/T/protoc-3.21.7-osx-x86_64.exe
Successfully extracted the library files.
Jul 12, 2023 11:27:00 AM io.ballerina.protoc.protobuf.cmd.GrpcCmd generateBalFile
SEVERE: An error occurred when generating the proto descriptor.
io.ballerina.protoc.protobuf.exception.CodeGeneratorException: Invalid command syntax. Stream closed
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:110)
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:83)
	at io.ballerina.protoc.protobuf.cmd.DescriptorsGenerator.generateRootDescriptor(DescriptorsGenerator.java:148)
	at io.ballerina.protoc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:251)
	at io.ballerina.protoc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:165)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:53)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:105)
	... 6 more

An error occurred when generating the proto descriptor. Invalid command syntax. Stream closed
```
This has 2 problems:
- The `grpc` command has crashed. This is not a good look to have the runtime crash.
- No explanation for the failure. Only says invalid command syntax.

### PR DESCRIPTION
**Pull request by ARYPROGRAMMER**
Fixes https://github.com/ballerina-platform/ballerina-library/issues/4656 - Improves error diagnostics when bal grpc command processes invalid proto files.

Problem: When processing invalid proto files, the command crashed with unhelpful IOException: Stream closed errors instead of displaying the actual protoc compiler error messages.

Root Cause: The handleProcessExecutionErrors() method was checking the process exit value before reading the error stream, causing the stream to close prematurely.

Solution:

- Read error stream BEFORE checking process exit value to prevent stream closure
- Added formatProtoError() helper method to format user-friendly error messages
- Errors now include file name, line number, and clear descriptions from protoc

Examples

Before (Bad):

```ballerina
SEVERE: An error occurred when generating the proto descriptor.
io.ballerina.protoc.protobuf.exception.CodeGeneratorException: Invalid command syntax. Stream closed
    at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(...)
Caused by: java.io.IOException: Stream closed
```

After
```ballerina
Error: Failed to generate Ballerina files from proto definition.

Proto compilation failed with the following error:
user_service.proto:3:14: "User" is not defined.
user_service.proto:4:14: "Pagination" is not defined.

Please check your .proto file for syntax errors and undefined types.
```

Test Cases
- Undefined message types: Shows clear "Type is not defined" messages
- Syntax errors: Shows specific line/column with syntax issue
- Valid protos: Continue to work correctly (regression test)

Checklist
- [x] Linked to an issue (https://github.com/ballerina-platform/ballerina-library/issues/4656)
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec

### CODE REVIEW

**Comment by ARYPROGRAMMER** [comment]
@daneshk can you please review this

**Comment by daneshk** [comment]
> @daneshk can you please review this

@ARYPROGRAMMER Seems like we have duplicate methods. Shall we have one?

**Comment by ARYPROGRAMMER** [comment]
> > @daneshk can you please review this
> 
> @ARYPROGRAMMER Seems like we have duplicate methods. Shall we have one?

Give me some time I'll just see once

**Comment by ARYPROGRAMMER** [comment]
> > @daneshk can you please review this
> 
> @ARYPROGRAMMER Seems like we have duplicate methods. Shall we have one?

yeah saw that lgtm now

@daneshk

**Comment by daneshk** [comment]
@ARYPROGRAMMER I just went through the original code. We mistakenly duplicate whole `BalFileGenerationUtils.java` inside the utils package. we should remove the one in the utils package and use the one in the core package. Shall we do it in the same PR? So that we need one place do the change.

**Comment by ARYPROGRAMMER** [comment]
> @ARYPROGRAMMER I just went through the original code. We mistakenly duplicate whole `BalFileGenerationUtils.java` inside the utils package. we should remove the one in the utils package and use the one in the core package. Shall we do it in the same PR? So that we need one place do the change.

yes absolutely we can do that. just check once my changes in few minutes

**Comment by ARYPROGRAMMER** [comment]
@daneshk i have did exactly what you wanted. let's see if this this you like it

**Comment by ARYPROGRAMMER** [comment]
@daneshk this should fix the checkstyle error

File: protoc-core/src/main/java/io/ballerina/protoc/core/BalFileGenerationUtils.java [hunk 1]
```diff
@@ -100,21 +102,53 @@ public static Process runProcess(String command) throws IOException {
...
+     *
+     * @param rawError The raw error output from protoc
+     * @return A formatted, user-friendly error message
+     */
+    private static String formatProtoError(String rawError) {
+    StringBuilder formatted = new StringBuilder();
+    formatted.append("Error: Failed to generate Ballerina files from proto definition.")
+        .append(System.lineSeparator());
+    formatted.append(System.lineSeparator());
+    formatted.append("Proto compilation failed with the following error:")
```
Comment (daneshk) [inline protoc-core/src/main/java/io/ballerina/protoc/core/BalFileGenerationUtils.java]: This is not formatted correctly. can you check

Comment (ARYPROGRAMMER) [reply protoc-core/src/main/java/io/ballerina/protoc/core/BalFileGenerationUtils.java]: resolved i believe

**Comment by ARYPROGRAMMER** [comment]
really worked hard on this, glad to contribute - hope this time everything is resolved

**Comment by ARYPROGRAMMER** [comment]
let me know if anything needed here, thanks @daneshk

**Comment by ARYPROGRAMMER** [comment]
can this be merged today @daneshk

**Review by daneshk — APPROVED** [review]
LGTM

**Comment by daneshk** [comment]
@ARYPROGRAMMER Thanks for the contribution.
