### PR TITLE
Fix extra line in generated ballerina source in grpc tool

### LINKED ISSUE #3953: Extra line is included in generated ballerina source in grpc tool
**Description:**
Extra line is included in generated ballerina source in grpc tool ([sample source](https://github.com/ballerina-guides/ballerina-in-action-samples/blob/6e9f6d9186a6bcd31c927cb007fb215623e5359b/grpc_api/descriptor_record_store_pb.bal#L166))

### PR DESCRIPTION
**Pull request by randilt**
- Resolved an issue where generated ballerina source files for grpc tool contained extra trailing newlines.
- Updated the writeOutputFile method to ensure only one newline at the end of each generated file.
- Added a test case to verify the newline handling.

## Purpose

Resolves [#3953](https://github.com/ballerina-platform/ballerina-library/issues/3953)

## Checklist
- [x] Linked to an issue
- [ ] Updated the changelog
- [x] Added tests
- [ ] Updated the spec

### CODE REVIEW

File: tooling-tests/src/test/java/io/ballerina/protoc/tools/ToolingCommonTest.java [hunk 1]
```diff
@@ -347,4 +347,39 @@ public void testImportsWithEnums() {
...
+                index--;
+                }
+                
+                //if the newline count is not 1, fail the test
+                Assert.assertEquals(newlineCount, 1, 
+                "Generated file should have exactly one newline at the end, found " + newlineCount);
+        } catch (IOException e) {
+                Assert.fail("Failed to read generated file", e);
+        }
+    }
```
Comment (daneshk) [inline tooling-tests/src/test/java/io/ballerina/protoc/tools/ToolingCommonTest.java]:
```suggestion
        try {
            Files.createDirectories(Paths.get(GENERATED_SOURCES_DIRECTORY, "tool_test_newline_test"));
        } catch (IOException e) {
            Assert.fail("Could not create target directories", e);
        }

        Path protoFilePath = Paths.get(RESOURCE_DIRECTORY.toString(), PROTO_FILE_DIRECTORY, "data-types", 
                "message.proto");
        Path outputDirPath = Paths.get(GENERATED_SOURCES_DIRECTORY, "tool_test_newline_test");
        Path generatedFile = outputDirPath.resolve("message_pb.bal");

        generateSourceCode(protoFilePath, outputDirPath, null, null);
        Assert.assertTrue(Files.exists(generatedFile), "Generated file does not exist");

        try {
            String content = Files.readString(generatedFile);
            int newlineCount = 0;
            int index = content.length() - 1;
                
            // check for newlines at the end of the file
            while (index >= 0 && content.charAt(index) == '\n') {
                newlineCount++;
                index--;
            }
                
            // if the newline count is not 1, fail the test
            Assert.assertEquals(newlineCount, 1, 
                "Generated file should have exactly one newline at the end, found " + newlineCount);
        } catch (IOException e) {
            Assert.fail("Failed to read generated file", e);
        }
    }
```

Comment (daneshk) [reply tooling-tests/src/test/java/io/ballerina/protoc/tools/ToolingCommonTest.java]: There is an indentation issue. Can you fix it?

Comment (randilt) [reply tooling-tests/src/test/java/io/ballerina/protoc/tools/ToolingCommonTest.java]: Hi @daneshk , I added the change you suggested, can you please check now?

**Review by daneshk — APPROVED** [review]
LGTM. Thank you, @randilt, for your contribution
